/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_4;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner obxScaner = new Scanner(System.in);
        System.out.println("introduce os cartos : ");
        int b100= (obxScaner.nextInt()/100);
        int r1= obxScaner.nextInt()%100;
        int b20= r1/20;
        int r2= r1%20;
        int b5= r2/5;
        int r3= r2%5;
        int moedas= r3/1;
        System.out.println("desglose : "+(("billetes de 100 = "+b100)+("\nbilletes de 20 = "+b20)+("\nbilletes de 5 = "+b5)+("\nmoedas 1€ = "+moedas)));
        
        
        
    }
}
