/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_5;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       double sueloFijo, importeVentas, numKm 
    }
}
