/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_3;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner obxScaner = new Scanner(System.in);
        System.out.println("primeiro moedas e logo billetes");
        System.out.println("introduza as moedas(so de 1€) : ");
        byte moeda=obxScaner.nextByte();
        System.out.println("introduza os billetes de 100 : ");
        byte b100=obxScaner.nextByte();
        System.out.println("introduzca os billetes de 20 : ");
        byte b20=obxScaner.nextByte();
        System.out.println("introduzca os billetes de 5 : ");
        byte b5=obxScaner.nextByte();
        System.out.println("visualizamos os cartos : "+((moeda*1)+(b100*100)+(b20*20)+(b5*5)));
    }
}
